/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VALTJU986jR
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
} from "@/components/ui/card";
import {
  Table,
  TableHeader,
  TableRow,
  TableHead,
  TableBody,
  TableCell,
} from "@/components/ui/table";
import { Recommendation } from "@/models";
import { EngagementDTO } from "@/types/engagement-dto";

export function Dashboard({
  engagements,
  recommendations,
}: {
  engagements: EngagementDTO[];
  recommendations: Recommendation[];
}) {
  return (
    <div className="flex flex-col h-full">
      <main className="flex-1 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 lg:grid-rows-2 gap-6 p-6">
        <Card className="col-span-1 lg:col-span-2 lg:row-span-2">
          <CardHeader>
            <CardTitle>User Engagement</CardTitle>
            <CardDescription>
              Detailed engagement data for each user and course type.
            </CardDescription>
          </CardHeader>
          <CardContent className="max-h-[20lh] overflow-y-scroll">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>User Name</TableHead>
                  <TableHead>Course Title</TableHead>
                  <TableHead>Timestamp</TableHead>
                  <TableHead>Time Spent</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {engagements?.map((engagement: EngagementDTO) => (
                  <TableRow key={engagement.id}>
                    <TableCell>{engagement.userName}</TableCell>
                    <TableCell>{engagement.courseTitle}</TableCell>
                    <TableCell>{engagement.timestamp}</TableCell>
                    <TableCell>{engagement.timeSpent}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Total Engagements</CardTitle>
            <CardDescription>
              The total number of engagements across all users and course types.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="text-5xl font-bold">{engagements.length}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Recommendations</CardTitle>
            <CardDescription>
              The number of recommendations given to users and the ratio of used
              recommendations.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              <div className="flex items-center justify-between">
                <div>Recommendations Given</div>
                <div className="text-2xl font-bold">
                  {recommendations?.length}
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </main>
    </div>
  );
}